name: ci

on:
  push:
    branches:
      - 'master'
      
jobs:
  build-netfx:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push
        working-directory: .
        run: |
          docker login -u $env:USER -p $env:TOKEN
          docker build -t buildtools:latest -m 2GB .
          docker image push hahaleyile/buildtools:latest
          docker logout
        env:
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
